name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Cross-build
      uses: izumin5210/action-go-crossbuild@v1.0.0
      with:
        name: my-app
        arch: amd64,arm64
        dest: ./dist
        os: darwin,linux,windows
        package: .
        goxz-version: v0.4.1

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: ./dist
